#!/usr/bin/env python3
# build_timeline.py —— 重建 metrics/timeline.yaml（生成物）← metrics/timeline.d/*.yaml（源）
#
# 为什么要有源/生成物这一层（2026-09-13，起因是提问"两个 PR 都生成了这个文件、同名怎么办"）：
#   `metrics/timeline.yaml` 原先**既是源、又是所有人 append 的目标**——而它是**一个列表文件**，
#   于是任意两个人各 append 一期都会撞在同一段文本上，冲突需要人判断"留哪一份"（判断错了就静默丢
#   一期读数）。实测这个冲突连"不同周"也会发生，因为大家写的是同一个文件的尾部。
#
#   改法与仓库既有模式一致（`knowledge/` 174 个 case 文件 + 生成的 `knowledge/_index.yaml`；
#   `proposals/ideas/` 58 张卡）：
#     源    `metrics/timeline.d/<期号>.yaml`   —— 一期一个文件，各人各写一个，不互相覆盖
#     生成物 `metrics/timeline.yaml`            —— 由本脚本从源重建，CI 校验一致性
#   冲突的性质因此改变：从"两个读数都在，你得判断留哪份"变成"重跑一次本脚本"（机械动作、无判断）。
#   读侧**完全不用改**：7 个读点继续读 `metrics/timeline.yaml`。
#
# 用法：
#   python3 scripts/build_timeline.py            # 重建（写文件）
#   python3 scripts/build_timeline.py --check    # CI：生成物与源是否一致（不一致即红并说明怎么修）
#   python3 scripts/build_timeline.py --print    # 只打印重建结果，不写文件
#
# 期号即文件名（期号本身由 verify_metrics 校验唯一）。排序按 (recorded_at, period)，
# 让"最上面是最新"不稳定——这里用**升序**（旧在前），与现有文件的历史顺序一致，便于人读趋势。

import argparse
import sys
from pathlib import Path

import yaml

SRC_DIR_REL = Path("metrics") / "timeline.d"
OUT_REL = Path("metrics") / "timeline.yaml"

HEADER = (
    "# GENERATED by scripts/build_timeline.py —— 不要直接编辑本文件。\n"
    "# 源：metrics/timeline.d/<期号>.yaml（一期一个文件，各人各写一个，不互相覆盖）。\n"
    "# 改法：改源文件（或新增一个），然后重跑 `python3 scripts/build_timeline.py`；\n"
    "# CI 的 metrics-validation job 用 `--check` 校验生成物与源一致。\n"
    "# 为什么这么分：原先本文件既是源又是 append 目标，两人各加一期就撞在同一段文本上，\n"
    "# 冲突要人判断留哪一份（判断错就静默丢一期读数）。改成「一期一文件 + 生成物」后，\n"
    "# 同一天的两人最多撞在各自那个小文件上，本文件的重建是机械动作。\n"
)


def load_yaml(path: Path):
    return yaml.safe_load(path.read_text(encoding="utf-8"))


def collect_sources(root: Path):
    """→ (periods, errors)。源目录不存在时返回空并如实说明（不假装有数据）。"""
    src_dir = root / SRC_DIR_REL
    errors = []
    if not src_dir.is_dir():
        return [], [f"源目录不存在：{SRC_DIR_REL}（本仓库的时序数据以它为源）"]
    periods = []
    seen = {}
    for f in sorted(src_dir.glob("*.yaml")):
        try:
            doc = load_yaml(f)
        except Exception as e:
            errors.append(f"{f.name}: YAML 解析失败：{e}")
            continue
        if not isinstance(doc, dict):
            errors.append(f"{f.name}: 顶层应为 mapping（一期一条记录）")
            continue
        p = doc.get("period")
        if not p:
            errors.append(f"{f.name}: 缺少 period")
            continue
        if p != f.stem:
            errors.append(f"{f.name}: 期号（{p}）与文件名不一致——期号即文件名，两者必须相同")
        if p in seen:
            errors.append(f"{f.name}: 期号 '{p}' 与 {seen[p]} 重复（趋势锚点必须唯一）")
        else:
            seen[p] = f.name
        periods.append(doc)
    # 排序：recorded_at 升序（缺失的排最后），同期按 period
    def key(d):
        ra = d.get("recorded_at")
        return (str(ra or "9999-99-99")[:10], str(d.get("period")))
    periods.sort(key=key)
    return periods, errors


def render(periods) -> str:
    body = yaml.safe_dump({"periods": periods}, allow_unicode=True, sort_keys=False,
                          default_flow_style=False)
    return HEADER + body


def main() -> int:
    ap = argparse.ArgumentParser(description="重建生成的 metrics/timeline.yaml（源：metrics/timeline.d/）")
    ap.add_argument("--check", action="store_true", help="校验生成物与源一致（CI 用）")
    ap.add_argument("--print", dest="do_print", action="store_true", help="只打印，不写文件")
    ap.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    args = ap.parse_args()
    root = args.root.resolve()

    periods, errors = collect_sources(root)
    if errors:
        print(f"{SRC_DIR_REL} 有 {len(errors)} 处问题：")
        for e in errors:
            print(f"  - {e}")
        return 1
    if not periods:
        print(f"{SRC_DIR_REL} 里没有任何期——时序数据层未落地")
        return 1

    out_path = root / OUT_REL
    wanted = render(periods)
    current = out_path.read_text(encoding="utf-8") if out_path.exists() else None

    if args.do_print:
        print(wanted)
        return 0

    if args.check:
        if current == wanted:
            print(f"timeline 生成物与源一致（{len(periods)} 期 ← {SRC_DIR_REL}/）")
            return 0
        print(f"{OUT_REL} 与源不一致——**不要手工改生成物**，跑一次重建即可：")
        print("  python3 scripts/build_timeline.py")
        if current is None:
            print(f"  （原因：{OUT_REL} 不存在）")
        else:
            try:
                cur_ids = [p.get("period") for p in (load_yaml(out_path) or {}).get("periods", [])]
            except Exception:
                cur_ids = None
            src_ids = [p.get("period") for p in periods]
            if cur_ids is not None and cur_ids != src_ids:
                print(f"  生成物期号：{cur_ids}")
                print(f"  源    期号：{src_ids}")
            else:
                print("  （期号相同、内容有差异：多半是源文件改了没重建）")
        return 1

    out_path.write_text(wanted, encoding="utf-8", newline="\n")
    print(f"已重建 {OUT_REL}（{len(periods)} 期 ← {SRC_DIR_REL}/）")
    for p in periods:
        print(f"  - {p.get('period'):<26} {p.get('kind')}")
    return 0


if __name__ == "__main__":
    from _stdio import pin_utf8_stdio
    pin_utf8_stdio()
    sys.exit(main())
