#!/usr/bin/env python3
# log_skill_exec.py —— 统一 skill 执行记录（run.md §4 机制 C 落地）
#
# 每次内容流程 skill 调用（diagnose / to-postmortem / to-reference / issue-ingest /
# knowledge-groom / replay）收尾时 append 一条执行记录到 metrics/skill-exec-log.yaml——
# 让 feedback loop 有全链路数据源（不只诊断侧），也让 evolve-check 收尾钩子有真实
# 现场记录可读（替代 agent 记忆"本轮做了什么"）。
#
# 记录字段（对齐 run.md §4 + execution §2 脱敏纪律）：
#   - skill + 版本（commit hash）+ 时间 + 触发者（session/task/人）
#   - 输入摘要：只记引用与聚合（issue 号 / 文件路径 / trace id），不落客户原文
#   - 产出：case/reference/卡 id 与状态流转
#   - 成本：token（估算或 DSH tokenMeter measured）
#   - decision_reason：关键决策一句话依据
# 边界：记录对象是 skill 与动作，不是人（roadmap 不做 KPI/身份/使用观测红线不变）
#
# 确定性 append（原则二）：脚本负责 YAML 写入，agent 只提供参数——避免手写破坏
# 多行结构（仓库教训：yaml.safe_dump roundtrip 会截断多行标量）。
#
# 用法：
#   python3 scripts/log_skill_exec.py --skill to-postmortem \
#     --products "VLLM-ASC-12345(submitted),VLLM-ASC-12346(submitted)" \
#     --reason "沉淀 2 条 #12345/#12346 case（S2 缺口驱动）" \
#     [--source issue-ingest] [--session <id>] [--tokens N] [--ref <issue>]

import argparse
import subprocess
import sys
from datetime import datetime
from pathlib import Path

import yaml

LOG_PATH = "metrics/skill-exec-log.yaml"
VALID_SKILLS = {
    "diagnose", "resume-diagnosis", "to-postmortem", "to-reference",
    "issue-ingest", "knowledge-groom", "s2-replay", "replay-golden",
    "evolve-check", "self-evolve", "capacity-health",
}


def git_head(root: Path) -> str:
    try:
        r = subprocess.run(["git", "rev-parse", "--short", "HEAD"],
                           capture_output=True, text=True, cwd=str(root))
        return r.stdout.strip() or "unknown"
    except Exception:
        return "unknown"


def main():
    ap = argparse.ArgumentParser(description="统一 skill 执行记录（append-only）")
    ap.add_argument("--skill", required=True, help="调用的 skill 名")
    ap.add_argument("--products", default="", help="产出（逗号分隔 id(状态)，如 VLLM-ASC-1(submitted)）")
    ap.add_argument("--reason", default="", help="关键决策一句话依据（decision_reason）")
    ap.add_argument("--source", default="", help="触发者来源（issue-ingest/self-evolve/人工/会话）")
    ap.add_argument("--session", default="", help="session id（如有）")
    ap.add_argument("--tokens", type=int, default=0, help="token 消耗（估算或 measured）")
    ap.add_argument("--cost-source", default="estimate", choices=["estimate", "measured"],
                    help="token 口径（measured = DSH tokenMeter）")
    ap.add_argument("--ref", default="", help="输入引用（issue 号/文件/trace，不含原文）")
    ap.add_argument("--root", type=Path, default=Path("."))
    args = ap.parse_args()
    root = args.root.resolve()

    if args.skill not in VALID_SKILLS:
        print(f"skill '{args.skill}' 不在合法集合 {sorted(VALID_SKILLS)}"); sys.exit(1)

    log_path = root / LOG_PATH
    # 读现有（保留）
    if log_path.exists():
        try:
            doc = yaml.safe_load(log_path.read_text(encoding="utf-8")) or {}
        except Exception:
            doc = {}
    else:
        doc = {}

    records = doc.get("records") or []
    entry = {
        "seq": len(records) + 1,
        "skill": args.skill,
        "version": git_head(root),
        "at": datetime.now().isoformat(timespec="seconds"),
        "source": args.source or "manual",
    }
    if args.session:
        entry["session"] = args.session
    if args.ref:
        entry["ref"] = args.ref
    if args.products:
        # 解析 products：id(状态) 逗号分隔（id 本身不含逗号）
        entry["products"] = []
        for p in args.products.split(","):
            p = p.strip()
            if not p:
                continue
            if "(" in p and p.rstrip().endswith(")"):
                pid, _, st = p.rstrip()[:-1].partition("(")
                entry["products"].append({"id": pid.strip(), "status": st.strip()})
            else:
                entry["products"].append({"id": p})
    if args.reason:
        entry["decision_reason"] = args.reason
    if args.tokens:
        entry["cost"] = {"tokens": args.tokens, "source": args.cost_source}

    records.append(entry)
    doc["_comment"] = ("GENERATED by scripts/log_skill_exec.py；统一 skill 执行记录（run.md §4）。"
                       "append-only——只追加不修改，供 evolve-check 收尾读现场 + metrics 全链路归因。"
                       "记录对象是 skill/动作/产物 id，非人（roadmap 不做 KPI/身份 红线）。")
    doc["records"] = records

    # 写回：文本级构建（每 record 手动序列化，避免 safe_dump 破坏中文/多行）
    out = [f"# {doc['_comment']}", "", "records:"]
    for r in records:
        out.append(f"- seq: {r['seq']}")
        out.append(f"  skill: {r['skill']}")
        out.append(f"  version: {r['version']}")
        out.append(f"  at: {r['at']}")
        out.append(f"  source: {r['source']}")
        if r.get("session"):
            out.append(f"  session: {r['session']}")
        if r.get("ref"):
            out.append(f"  ref: '{r['ref']}'")
        if r.get("products"):
            out.append("  products:")
            for p in r["products"]:
                if p.get("status"):
                    out.append(f"    - id: {p['id']}")
                    out.append(f"      status: {p['status']}")
                else:
                    out.append(f"    - id: {p['id']}")
        if r.get("decision_reason"):
            out.append(f"  decision_reason: '{r['decision_reason']}'")
        if r.get("cost"):
            out.append(f"  cost: {{tokens: {r['cost']['tokens']}, source: {r['cost']['source']}}}")
    log_path.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"exec-log: seq {entry['seq']} 已记录（{args.skill}）→ {log_path}")


if __name__ == "__main__":
    main()
